Fix ownership of /home/build/.local/share/containers
Fixes: https://github.com/containers/buildah/issues/3457

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

diff --git a/tests/validate/buildahimages-are-sane b/tests/validate/buildahimages-are-sane
--- a/tests/validate/buildahimages-are-sane
+++ b/tests/validate/buildahimages-are-sane
@@ -44,6 +44,13 @@ function build_and_check() {
         exit 1
     fi
 
+    owner=$(buildah run $ctr stat -c "%U:%G" /home/build/.local/share/containers)
+    if [[ "${owner}" != "build:build" ]]; then
+        echo "$ME: ownership of /home/build/.local/share/containers failed on $dir:"
+        echo "  ${owner}"
+        exit 1
+    fi
+
     bin/buildah rm $ctr &>/dev/null
     bin/buildah rmi buildah &>/dev/null
 }
